[package]
name = "terraffi_gen"
description = "C header file generation for Rust libraries exposing a C interface via terraffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
convert_case = "0.11"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
cargo_metadata = { version = "0.23"}
terraffi_helpers = { path = "../terraffi_helpers", version = "0.1.0" }
