use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{DeriveInput, Expr, Meta, parse_macro_input};
use terraffi_helpers::{has_no_mangle, is_repr_c, is_repr_transparent};

/// Adding this macro to a type will force it to be exported to a terraffi header.
/// It's also useful to verify at compile time that the type will successfully be exportable.
///
/// Produces compile errors if:
/// - Applied to anything other than a struct, enum, function, or constant.
/// - Applied to a struct or enum that is not `#[repr(C)]`.
/// - Applied to a function that is not `pub`, not `extern "C"`, or missing `#[unsafe(no_mangle)]`.
#[proc_macro_attribute]
pub fn terraffi_export(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let item_clone = item.clone();
    let parsed: syn::Item = match syn::parse(item_clone) {
        Ok(i) => i,
        Err(_) => return item,
    };

    let errors = validate_terraffi_export(&parsed);
    if errors.is_empty() {
        return item;
    }

    let mut output: proc_macro2::TokenStream = item.into();
    for err in errors {
        output.extend(err.to_compile_error());
    }
    output.into()
}

/// Adding this macro to a type will prevent it to be exported to a terraffi header.
#[proc_macro_attribute]
pub fn terraffi_ignore(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Attributes macro for terraffi configuration
#[proc_macro_attribute]
pub fn terraffi(_attr: TokenStream, item: TokenStream) -> TokenStream {
    item
}

/// Derive macro that generates a companion enum for discriminated which only contains the discriminants and no data.
/// This type will be automatically generated by terraffi in an exported header when a discriminated enum is exported
/// but using this macro will additionally add it to your rust code.
///
/// The kind enum name defaults to `{EnumName}Kind`. To customize it, use
/// the `terraffi` helper attribute:
///
/// ```ignore
/// #[derive(DiscriminantEnum)]
/// #[terraffi(discriminant_enum_name = "MyEnumTag")]
/// #[repr(C)]
/// pub enum MyEnum { ... }
/// ```
///
/// The discriminant method name defaults to `kind`. To customize it:
///
/// ```ignore
/// #[derive(DiscriminantEnum)]
/// #[terraffi(discriminant_method_name = "tag")]
/// #[repr(C)]
/// pub enum MyEnum { ... }
/// ```
///
/// To add extra derives to the generated kind enum, use `additional_derives`:
///
/// ```ignore
/// #[derive(DiscriminantEnum)]
/// #[terraffi(additional_derives = derive(Serialize, Deserialize))]
/// #[repr(C)]
/// pub enum MyEnum { ... }
/// ```
#[proc_macro_derive(DiscriminantEnum, attributes(terraffi))]
pub fn derive_discriminant_enum(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let enum_name = &input.ident;

    let data = match &input.data {
        syn::Data::Enum(data) if data.variants.iter().any(|v| !v.fields.is_empty()) => data,
        _ => {
            return syn::Error::new_spanned(
                &input.ident,
                "DiscriminantEnum can only be derived for discriminated enums",
            )
            .to_compile_error()
            .into();
        }
    };

    let has_data_variants = data
        .variants
        .iter()
        .any(|v| !matches!(v.fields, syn::Fields::Unit));

    if !has_data_variants {
        return TokenStream::new();
    }

    // Check for #[terraffi(discriminant_enum_name = "CustomName")] attribute
    let kind_name =
        parse_kind_name_attr(&input.attrs).unwrap_or_else(|| format_ident!("{}Kind", enum_name));

    // Check for #[terraffi(discriminant_method_name = "custom_name")] attribute
    let method_name = parse_str_attr(&input.attrs, "discriminant_method_name")
        .unwrap_or_else(|| format_ident!("kind"));

    // Check for #[terraffi(additional_derives = derive(Serialize, Deserialize))]
    let additional_derives = parse_additional_derives_attr(&input.attrs);

    let vis = &input.vis;

    let variants: Vec<_> = data
        .variants
        .iter()
        .map(|v| {
            let ident = &v.ident;
            match &v.discriminant {
                None => quote! { #ident },
                Some((_, e)) => quote! { #ident = #e },
            }
        })
        .collect();

    let variant_match: Vec<_> = data
        .variants
        .iter()
        .map(|v| {
            let ident = &v.ident;
            if v.fields.is_empty() {
                quote! { #enum_name::#ident => Self::#ident }
            } else {
                quote! { #enum_name::#ident { .. } => Self::#ident }
            }
        })
        .collect();

    let additional_derive_attr = additional_derives.map(|tokens| {
        quote! { #[derive(#tokens)] }
    });

    let expanded = quote! {
        #[repr(C)]
        #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
        #additional_derive_attr
        #vis enum #kind_name {
            #(#variants),*
        }

        impl #enum_name {
            pub fn #method_name(&self) -> #kind_name {
                self.into()
            }
        }

        impl From<&#enum_name> for #kind_name {
            fn from(value: &#enum_name) -> Self {
                match value {
                    #(#variant_match),*,
                }
            }
        }

        impl From<#enum_name> for #kind_name {
            fn from(value: #enum_name) -> Self {
                match value {
                    #(#variant_match),*,
                }
            }
        }
    };

    TokenStream::from(expanded)
}

fn parse_additional_derives_attr(attrs: &[syn::Attribute]) -> Option<proc_macro2::TokenStream> {
    for attr in attrs {
        if !attr.path().is_ident("terraffi") {
            continue;
        }
        if let Meta::List(meta_list) = &attr.meta
            && let Ok(nested) = meta_list.parse_args_with(
                syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated,
            )
        {
            for meta in &nested {
                if let Meta::NameValue(nv) = meta
                    && nv.path.is_ident("additional_derives")
                    && let Expr::Call(call) = &nv.value
                {
                    let args = &call.args;
                    return Some(quote! { #args });
                }
            }
        }
    }
    None
}

fn validate_terraffi_export(item: &syn::Item) -> Vec<syn::Error> {
    match item {
        syn::Item::Struct(s) => {
            if s.fields.len() == 1 && !is_repr_c(&s.attrs) && !is_repr_transparent(&s.attrs) {
                vec![syn::Error::new_spanned(
                    &s.ident,
                    "#[terraffi_export] on a single field struct requires #[repr(C)] or #[repr(transparent)]",
                )]
            } else if s.fields.len() > 1 && is_repr_transparent(&s.attrs) {
                vec![syn::Error::new_spanned(
                    &s.ident,
                    "#[terraffi_export] cannot export a #[repr(transparent)] struct with multiple fields",
                )]
            } else if s.fields.len() > 1 && !is_repr_c(&s.attrs) {
                vec![syn::Error::new_spanned(
                    &s.ident,
                    "#[terraffi_export] on a struct with multiple fields requires #[repr(C)]",
                )]
            } else {
                vec![]
            }
        }
        syn::Item::Enum(e) => {
            if !is_repr_c(&e.attrs) {
                vec![syn::Error::new_spanned(
                    &e.ident,
                    "#[terraffi_export] on an enum requires #[repr(C)]",
                )]
            } else {
                vec![]
            }
        }
        syn::Item::Fn(f) => {
            let mut errors = Vec::new();

            // Check public visibility
            if !matches!(f.vis, syn::Visibility::Public(_)) {
                errors.push(syn::Error::new_spanned(
                    &f.sig.ident,
                    "#[terraffi_export] functions must be `pub`",
                ));
            }

            // Check extern "C" ABI
            let is_extern_c = f
                .sig
                .abi
                .as_ref()
                .is_some_and(|abi| abi.name.as_ref().is_some_and(|name| name.value() == "C"));
            if !is_extern_c {
                errors.push(syn::Error::new_spanned(
                    &f.sig.ident,
                    "#[terraffi_export] functions must be `extern \"C\"`",
                ));
            }

            // Check for #[unsafe(no_mangle)] or #[no_mangle]
            if !has_no_mangle(&f.attrs) {
                errors.push(syn::Error::new_spanned(
                    &f.sig.ident,
                    "#[terraffi_export] functions must have #[unsafe(no_mangle)]",
                ));
            }

            errors
        }
        syn::Item::Const(_) => vec![],
        _ => vec![syn::Error::new(
            proc_macro2::Span::call_site(),
            "#[terraffi_export] can only be applied to structs, enums, functions, or constants",
        )],
    }
}

fn parse_str_attr(attrs: &[syn::Attribute], key: &str) -> Option<syn::Ident> {
    for attr in attrs {
        if !attr.path().is_ident("terraffi") {
            continue;
        }
        if let Meta::List(meta_list) = &attr.meta
            && let Ok(nested) = meta_list.parse_args_with(
                syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated,
            )
        {
            for meta in &nested {
                if let Meta::NameValue(nv) = meta
                    && nv.path.is_ident(key)
                    && let Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Str(s),
                        ..
                    }) = &nv.value
                {
                    return Some(format_ident!("{}", s.value()));
                }
            }
        }
    }
    None
}

fn parse_kind_name_attr(attrs: &[syn::Attribute]) -> Option<syn::Ident> {
    parse_str_attr(attrs, "discriminant_enum_name")
}
